services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - es-net

  app:
    build: .
    container_name: malicious_app
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - INDEX_NAME=my_index
      - CSV_PATH=/app/data_files/tweets_injected_3.csv
      - WEAPONS_FILE=/app/data_files/weapon_list.txt
    networks:
      - es-net
    volumes:
      - .:/app

networks:
  es-net:
    driver: bridge
